#include "stm32c0xx_ll_gpio.h"
#include "stm32c0xx_ll_exti.h"

#define NRST_PIN LL_GPIO_PIN_2
#define NRST_PORT GPIOF

#define USART_TX_PIN LL_GPIO_PIN_14
#define USART_TX_PORT GPIOC

#define USART_RX_PIN LL_GPIO_PIN_2
#define USART_RX_PORT GPIOB

#define USELESS_BUTTON_PIN LL_GPIO_PIN_15
#define USELESS_BUTTON_PORT GPIOC

#define SERVO1_PIN LL_GPIO_PIN_7
#define SERVO1_PORT GPIOB
#define SERVO2_PIN LL_GPIO_PIN_0
#define SERVO2_PORT GPIOA
#define SERVO3_PIN LL_GPIO_PIN_1
#define SERVO3_PORT GPIOA
#define SERVO4_PIN LL_GPIO_PIN_2
#define SERVO4_PORT GPIOA
#define SERVO5_PIN LL_GPIO_PIN_5
#define SERVO5_PORT GPIOA
#define SERVO6_PIN LL_GPIO_PIN_3
#define SERVO6_PORT GPIOB

#define SWITCH1_PIN LL_GPIO_PIN_3
#define SWITCH1_PORT GPIOA
#define SWITCH1_EXTI_LINE LL_EXTI_LINE_3
#define SWITCH2_PIN LL_GPIO_PIN_4
#define SWITCH2_PORT GPIOA
#define SWITCH2_EXTI_LINE LL_EXTI_LINE_4
#define SWITCH3_PIN LL_GPIO_PIN_6
#define SWITCH3_PORT GPIOA
#define SWITCH3_EXTI_LINE LL_EXTI_LINE_6
#define SWITCH4_PIN LL_GPIO_PIN_7
#define SWITCH4_PORT GPIOA
#define SWITCH4_EXTI_LINE LL_EXTI_LINE_7
#define SWITCH5_PIN LL_GPIO_PIN_11
#define SWITCH5_PORT GPIOA
#define SWITCH5_EXTI_LINE LL_EXTI_LINE_11

#define SWDIO_PIN LL_GPIO_PIN_13
#define SWDIO_PORT GPIOA
#define SWCLK_PIN LL_GPIO_PIN_14
#define SWCLK_PORT GPIOA